#!/usr/bin/env bash

###  ------------------------------- ###
###  Helper methods for BASH scripts ###
###  ------------------------------- ###

if ! which jazzy >/dev/null; then
  echo "Jazzy not detected: You can download it from https://github.com/realm/jazzy"
  exit
fi

# Docs by jazzy
# https://github.com/realm/jazzy
# ------------------------------
jazzy --min-acl internal -x -workspace,Superhero.xcworkspace,-scheme,Superhero
